# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk12

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres
  - psql -c 'create database ParserSQLru;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - stas.korobeinikov@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="699061af-0629-4e23-b4e0-91e70898f02d"

